name: '🐛 反馈 Bug'
description: '反馈一个问题/缺陷'
title: '[Bug] '
labels: ['bug']
body:
  - type: dropdown
    attributes:
      label: '📦 部署方式'
      multiple: true
      options:
        - '本地部署'
        - 'Docker'
        - 'Vercel'
        - 'Other'
    validations:
      required: true
  - type: input
    attributes:
      label: '📌 软件版本'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: '💻 系统环境'
      multiple: true
      options:
        - 'Windows'
        - 'macOS'
        - 'Ubuntu'
        - 'Other Linux'
        - 'iOS'
        - 'iPad OS'
        - 'Android'
        - 'Other'
    validations:
      required: true
  - type: input
    attributes:
      label: '📌 系统版本'
    validations:
      required: false
  - type: textarea
    attributes:
      label: '🐛 问题描述'
      description: 请提供一个清晰且简洁的问题描述，若上述选项为`Other`，也请详细说明。
    validations:
      required: true
  - type: input
    attributes:
      label: '💬 对话分享链接'
      description: 如果要反馈工具调用类问题，请附带相关对话的分享链接
  - type: textarea
    attributes:
      label: '📷 复现步骤'
      description: 请提供一个清晰且简洁的描述，说明如何复现问题。
  - type: textarea
    attributes:
      label: '🚦 期望结果'
      description: 请提供一个清晰且简洁的描述，说明您期望发生什么。
  - type: textarea
    attributes:
      label: '📝 补充信息'
      description: 如果您的问题需要进一步说明，或者您遇到的问题无法在一个简单的示例中复现，请在这里添加更多信息。
